language: java

sudo: required

# required for oraclejdk9
dist: xenial

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "HHTP5GsbRnB+wgO3oVW/8V+M7Qg8V95XACfdFpg9XdLIytzpI/S5y0nohXKb36GU7JfjT8TNuZ7To3+Qg+Ws7mFzojvcpHagkHFaidftskqsWvaj7L0uEERomGxwrqoe6gMVDP29pMeG7TZmQCVD8sA6k/kqSMnzycPTWP2unCHfL3h8YLtTl44lvsOA2XrV4Q0PNjS+g6umxKbbNSi5Lin37NwCQ/lxZx8Dcoy8sXQK9APOgOl34qA0z33ovRkCBmRhUG1J/D/tDh+MTSbnYpg5X8SUGJONfaYMKD5wjM+YkOeq1aG2HaWFOKv0cQVQesTaiaNVZ15zlUrKMqMb3JL1nShTmQR2lm1CSrMM2a1aIh5C4dm+QkcycPr07NM8MUOeE00sAurd48X2xsFmuHp3va30Exb+YJBzDOG+K2vuLgV5BH93VxCs5Qn1su41jitYXCs+iV/+NzRYNs16SqVvsZDUGObqNe+rQXNBCZlvwfZEjXVKYoij4eQl8EG2qzwNL+yrTt+52VNNmtBOD8T1tlMyBeHgZv8RCMem3uEm91VWXQ2juy8azJDytnE6HVXuAWP1Y1PD35yTr3SdnDxZnGplaBQYTWglJXxW4Df000dnvF/g3xQtjLT72o2zmDngW+V6AjMGyNZLyZhi87Yl0BSH1owdVW96lsVRRG8="

before_install:
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then
      echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-;
    fi

install:
  - cp travis-toolchains.xml ~/.m2/toolchains.xml

script:
   # Run Build when not on coverity branch.
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then
      ./mvnw clean install -Dmaven.test.skip=true;
    fi

after_success:
     # Upload coveralls when not on coverity branch.
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then
      ./mvnw clean cobertura:cobertura coveralls:report;
      ./mvnw clean install -Dmaven.test.failure.ignore=true cobertura:cobertura sonar:sonar;
    fi

addons:
  sonarqube: true
  coverity_scan:
    project:
      name: "rajendarreddyj/development-java"
    notification_email: rajendarreddyj@gmail.com
    build_command_prepend: "mvn clean"
    build_command:   "./mvnw -DskipTests=true compile"
    branch_pattern: coverity_scan

notifications:
  slack:
    on_success: never  # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: never    # options: [always|never|change] default: always
