
package org.example.contactwsdlfile;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ContactWSDLFile", targetNamespace = "http://www.example.org/ContactWSDLFile/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ContactWSDLFile {


    /**
     * 
     * @param parameters
     * @return
     *     returns org.example.contactwsdlfile.GetContactOperationResponse
     */
    @WebMethod(action = "http://www.example.org/ContactWSDLFile/getContactOperation")
    @WebResult(name = "getContactOperationResponse", targetNamespace = "http://www.example.org/ContactWSDLFile/", partName = "parameters")
    public GetContactOperationResponse getContactOperation(
        @WebParam(name = "getContactOperationRequest", targetNamespace = "http://www.example.org/ContactWSDLFile/", partName = "parameters")
        GetContactOperationRequest parameters);

}
